{% set version = "5.2.2" %}

package:
  name: giflib
  version: {{ version }}

source:
  - url: https://downloads.sourceforge.net/project/giflib/giflib-{{ version }}.tar.gz
    sha256: be7ffbd057cadebe2aa144542fd90c6838c6a083b5e8a9048b8ee3b66b29d5fb
    patches:
      - fix_win.patch    # [win]
      - stdbool_h.patch  # [win]
  # add a getopt polyfill
  - path: getopt.h       # [win]

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    # SONAME changes at minor revs.
    #    https://abi-laboratory.pro/tracker/timeline/giflib/
    - {{ pin_subpackage('giflib', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make        # [not win]
    - m2-patch    # [win]
    - cmake

test:
  commands:
    - gifbuild -h
    - giffix -h
    - giftext -h
    - gifclrmp -h
    - gif2rgb -h

about:
  home: https://giflib.sourceforge.net
  license: MIT
  license_family: MIT
  license_file:
    - COPYING
    - getopt_LICENSE.txt  # [win]
  summary: Library for reading and writing gif images
  description: |
    The GIFLIB project maintains the giflib service library, which has been pulling images
    out of GIFs since 1989. It is deployed everywhere you can think of and some places you
    probably can't - graphics applications and web browsers on multiple operating systems,
    game consoles, smartphones, and likely your ATM too.
  dev_url: https://sourceforge.net/p/giflib/code/ci/master/tree
  doc_url: https://sourceforge.net/p/giflib/wiki/Home

extra:
  recipe-maintainers:
    - ocefpaf
    - 183amir
    - msarahan
    - isuruf
    - wolfv
    - katietz

